server:
  port: 8888
  main:
    web-application-type: none
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: mcp
  ai:
    openai:
      api-key:
      base-url:
    mcp:
      client:
        sse:
          connections:
            server1:
              url: http://localhost:8080
  mandatory-file-encoding: UTF-8

# 调试日志
logging:
  level:
    io:
      modelcontextprotocol:
        client: DEBUG
        spec: DEBUG


ai:
  user:
    input: "123"